### ISSUE TITLE
Why the asymmetry in Performance Testing?

### ISSUE THREAD

**Issue by iriszero** [microsoft/msquic#1035]
In the Performance dashboard, `Windows User(OpenSSL)` and `Windows User(SChannel)` show asymmetric throughput. Could we get why this has happened?

On my Ubuntu setting, both upload and download recorded almost the same, around 1.25 Gbps.

**Comment by nibanks** [comment]
We have an OS limitation around connected sockets and RSS on Windows. There is no way for the user mode application to align with the RSS core. This is what ends up (most of the time) resulting in the lower performance for user mode downloads (at high rates).

It's on the books for our next Windows release to hopefully fix, but we'll see.

**Comment by iriszero** [comment]
@nibanks could you share the environment details of the testing, whose result is shown in the dashboard?

It's the best among what I've seen, around 6Gbps.

I'm especially curious about
i) # of connections on the client and server
ii) # of the CPU cores used (rather than just equipped) on the client and server
iii) UDP GSO (LSO) on/off
iv) cipher suite (NOTE: whether CBC or GSM does matter)
v) congestion algorithm

Always appreciate quick and very helpful responses from maintainers.
I don't mean to be invasive; I understand some (or all) of these may well be considered as trade secret, as have not released by others.

**Comment by nibanks** [comment]
@iriszero https://github.com/microsoft/msquic/wiki/Performance has some of the information you want. It has the HW specs of the test machines. It also has a link the the perf spec we follow when doing performance testing.

As to specific answers:

i) 1 connection on both client and server machines (this is a dedicated perf test environment).
ii) In the tput tests, usually 2 cores end up being used on both client and server, because of how thread scheduling works; though it's possible sometimes only one will.
iii) This is on the latest Windows Server Insider Previous builds, which has UDP send and receive batching/coalescing support in the OS. (No HW offloads for these are enabled at this time).
iv) TLS_AES_256_GCM_SHA384
v) Cubic
