### ISSUE TITLE
range.h: check bounds by default

### ISSUE THREAD

**Issue by DemiMarie** [microsoft/msquic#1043]
For security reasons, it would be nice if the various `range.h` functions always checked that accesses are within bounds, and crashed the process if they were not.  Currently, the default is to not check.

https://github.com/microsoft/msquic/blob/6a7fefc053f7769d2fca825e3c0848e1003d688a/src/core/range.h#L88-L96

**Comment by nibanks** [comment]
The function right after that in the file is `QuicRangeGetSafe`:

https://github.com/microsoft/msquic/blob/6a7fefc053f7769d2fca825e3c0848e1003d688a/src/core/range.h#L102-L110

There are two because it allows for optimization at the caller layer. Some callers already know; some do not. We have a lot of static analysis to validate these assumptions as well.

I'm going to close this, but feel free to add additional questions/comments.

**Comment by DemiMarie** [comment]
Personally, I would prefer `QuicRangeGet` to be the safe version, and for the unsafe version to be named `QuicRangeGetUnsafe`.  While a NULL pointer dereference is still UB in C, in practice (assuming one compiles with `-fno-delete-null-pointer-checks`) it is a non-exploitable crash.  Out-of-bounds array accesses, however, are often exploitable.  So I would like to only use the unsafe version when there is a proof (explained in a comment at the call site) that it is safe.

**Comment by nibanks** [comment]
I'd be willing to take a PR for that rename if you're willing to make it.
