### ISSUE TITLE
Sample client error: 0x80410003

### ISSUE THREAD

**Issue by okbaswc** [microsoft/msquic#1138]
I generated a self-signed cert and run the server with the thumbprint, without error:

`./quicsample.exe -server -cert_hash:B0B02D2AE27E0CAEB723107224DCF79052352466`

However, when I run the client in another Powershell on the same machine, I get:

_"Shut down by transport, 0x80410003"_

Is this an invalid parameter error?

I've tried, with and without -unsecure:
`./quicsample.exe -client -target:127.0.0.1 -unsecure`
`./quicsample.exe -client -target:localhost -unsecure`
`./quicsample.exe -client -target:127.0.0.1:4567 -unsecure`
`./quicsample.exe -client -target:localhost:4567 -unsecure`

Is this a bug or am I doing something incorrectly? I've run the prepare machine script, have insider build with TLS 1.3, etc. just can't seem to connect the samples.

**Comment by ThadHouse** [comment]
When you created the certificate, did you include `localhost` in the DnsName powershell command? Even with the -unsecure flag, the SNI passed for target must be listed on the certificate. If the SNI does not match, the connection will always be refused, even with a self signed certificate.

**Comment by okbaswc** [comment]
Yes, the command I used:

`New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "cert:\CurrentUser\My"`

**Comment by ThadHouse** [comment]
Currently, the latest builds from main do not work with even the latest insider builds, but require internal builds, since they have support for the QUIC 1.0 changes. However, this can be worked around in 2 ways.

1. Force Version 29 on the client side. This can be done with the following code placed inside of `RunClient` after the call to `ConnectionOpen`. You'll need the move the variable to the top of the function to avoid the variable initialization warning.
```
uint32_t Version = 0xff00001dU;
    MsQuic->SetParam(Connection, QUIC_PARAM_LEVEL_CONNECTION, QUIC_PARAM_CONN_QUIC_VERSION, sizeof(Version), &Version);
```
2. Use the OpenSSL builds. These have the advantage of working on any Windows 10 version, and don't depend on any internal changes in windows. As of a few weeks ago, these can even use cert hashes and the windows cert store, as long as the certificates are marked as exportable when imported. In the powershell cert command, set `-KeyExportPolicy Exportable` for this to work.
