### ISSUE TITLE
Use 1200 Byte Minimum, not 1280

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1216]
### Describe the bug

The specs recommend that you use a 1200 byte minimum packet send when sending (to allow for tunneling + min IPv4 MTU) initial packets. MsQuic currently uses 1280, which doesn't allow for tunneling if the MTU is 1280. One reason we would prefer to send more is to give the server more "amplification credit" so it can send more back, to allow for larger server certificates. But the tunneling aspect might be more important.

We should investigate reducing the value used in MsQuic (btw, it's not as trivial as just decreasing the constant `QUIC_INITIAL_PACKET_LENGTH`).

**Comment by ThadHouse** [comment]
With the DPLPMTUD changes, this in theory now just works. However, our DPLPMTUD algorithm depended on 1280 for ideal incrementing logic. We should discuss what we want for a better algortithm before we do this.

The MTU is configurable down to 1248 currently, which is the smallest we can allow because 1200 is the packet size, not MTU.
