### ISSUE TITLE
Build Different CPU Architectures on Linux

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#122]
There is some initial cmake code to build different architectures but it is not implemented for Linux. We need to get x86, x64 and arm working, possibly arm64 (if possible).

**Comment by ThadHouse** [comment]
Do you want this to mean native compilation, or a way to do cross compilation? If just native, that's been fixed by my build changes that enabled building natively on the Pi, and this can be closed. If we want to support cross scenarios, we should rename this issue to make that clearer to external contributors.

**Comment by nibanks** [comment]
> Do you want this to mean native compilation, or a way to do cross compilation? If just native, that's been fixed by my build changes that enabled building natively on the Pi, and this can be closed. If we want to support cross scenarios, we should rename this issue to make that clearer to external contributors.

Cross-compilation. Just as a single Windows machine can build for all other architectures, it'd be nice to have that support for Linux.
