### ISSUE TITLE
Potential send packet reordering for user mode servers

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#1223]
Because of how the user mode datapath determines which OS socket to send a specific send on, there is a possibility for reordered packets to be sent if a packet pends.

The current CPU thread is used to get which socket is used to send on. If a send then pends, and the worker immediately sends another packet (as pending is treated as success above the datapath), its possible for the 2nd send to be assigned to a different socket because of a context switch. This would place the 2nd send in a different queue, which then could complete the send at any point, irrespective of the 1st send. This would be an out of order packet.

A relatively simple solution to this would be to pass the worker index down to the datapath, which could then use that to always grab the correct socket context, irrespective of how threads work.

This does not affect client sockets, as only 1 possible socket to send on exists. And as far as I can tell, kernel mode isn't affected because its high level socket abstraction has direct access to the os socket.

**Comment by nibanks** [comment]
Some thoughts I had:

We don't necessarily want to force the QUIC layer to always use the same socket for send as receive, I think. For instance, in single connection/stream high throughput performance tests, the thread scheduler ends up putting the QUIC thread on one core and the UDP thread/kernel on another. When this happens, we need to see what (if any) affect it would have to continue using the same socket. Is there contention, or not?

Though, it might be ok. Thinking about Windows kernel, there is only **one** socket anyways. But there are differences obviously between user mode and kernel, because there is a send buffer that the app's data might be copied into, and if multiple cores end up writing to that same buffer, there will be contention.
