### ISSUE TITLE
Can I ask why you want to limit the threads?

### ISSUE THREAD

**Issue by warm-dawn** [microsoft/msquic#1681]
Can I ask why you want to limit the threads?

_Originally posted by @nibanks in https://github.com/microsoft/msquic/issues/930#issuecomment-713273511_
====================================
There is such a use case:
I use message queue to synchronize io data.
Single-threaded read-write queues are much faster for multi-read and multi-write queues, and there is no order problem.
So I hope msquic can provide single-threaded mode.

**Comment by nibanks** [comment]
Every QUIC connection is already single threaded effectively. Every event on the connection and all child stream objects are delivered serially to the application. As for what is faster or not, MsQuic is designed with performance as a **primary** goal in mind, and because of that, currently have the higher performance numbers for any available QUIC stack (as far as I have seen). I would ask you to try what we currently have and if you can find a performance issue, we'd be very happy to help with any specific issue you find.
