### ISSUE TITLE
Performance problems with 1.8 when SendBufferingEnabled is FALSE

### ISSUE THREAD

**Issue by theandrewcross** [microsoft/msquic#1937]
We are sending video data over MSQUIC. In order to get the best possible performance we allow multiple simultaneous network sends to occur and try to keep about 8 video frames in flight when at all possible. It is very common that we are receiving and sending data at the same time across many streams.

We have found that when we send with `SendBufferingEnabled = TRUE`, then the performance on all sending is great and that calls to `StreamSend()` typically take <1ms to complete. 

When we send with `SendBufferingEnabled = FALSE`, then the average time taken to send always seems to be about ~41ms in many cases (but not all, some are very fast). 

It seems that this value of ~41ms is the same across many machines and when sending either large (150 kbytes) or small packets (1000 bytes). This is with 8 pending sends at any time.

We see the same problem when sending both to localhost or to another machine (which rules out network performance). 

Using msquic v1.4.0.0 did not show this problem, using version v1.8.0.0 does show it.

**Comment by nibanks** [comment]
Would you be able to collect some traces in both cases? You should be able to run:

- `.\scripts\log.ps1 -Start -Profile Performance.Verbose`
- `<repro>`
- `.\scripts\log.ps1 -Stop -OutputPath .\artifacts\quic -RawLogOnly`

Then collect `.\artifacts\quic.log` and the symbol files and share them.

**Comment by nibanks** [comment]
Also, besides that increased time to call the API, are there any other side effects? Did overall throughput decrease?

**Comment by theandrewcross** [comment]
> Would you be able to collect some traces in both cases? You should be able to run:
> 
> * `.\scripts\log.ps1 -Start -Profile Performance.Verbose`
> * `<repro>`
> * `.\scripts\log.ps1 -Stop -OutputPath .\artifacts\quic -RawLogOnly`
> 
> Then collect `.\artifacts\quic.log` and the symbol files and share them.

Please find it attached. This version showed a lot of the frames sending at ~40ms a frame, but not all (the process of logging seems to change the timing slightly of runs). 

[TimingProblemsRun.zip](https://github.com/microsoft/msquic/files/7041563/TimingProblemsRun.zip)

**Comment by theandrewcross** [comment]
> Also, besides that increased time to call the API, are there any other side effects? Did overall throughput decrease?

I cannot say for sure. The problem is that we allow for "8 outstanding sends at once" because each outstanding send is more memory. Our throughput definitely decreased but this might well be because we use a semaphore to keep the number of frames in flight to some reasonable number.

**Comment by theandrewcross** [comment]
ps. Let me thank you sincerely for your very timely responses. It truly is appreciated.

**Comment by nibanks** [comment]
The zip above only contains 1 etl file. Which scenario is it? I assume the problem one? Would you be able to collect traces for the good case too?

**Comment by nibanks** [comment]
Also, there don't seem to be any QUIC events in there. I might need you to try again for both scenarios.

**Comment by theandrewcross** [comment]
Let me get you a few more runs showing the difference. Give me a second to run the tests.

**Comment by nibanks** [comment]
BTW, if you want to jump [on Discord](https://discord.gg/YGAtCwTSsc) to chat, I'm available there as well.

**Comment by theandrewcross** [comment]
Sorry for the slow response, I have attached two runs: one with buffering and one without. To highlight the difference, I included the output of our application that shows the "milliseconds to send video". If you look at the one with buffering you will see that the send times are always tiny (0.03ms or so), but the one without has a large number that are at 40ms.

Sorry this took so long, it took some time to get the ETW compilation into our custom build scripts. I am happy to get any other information you need.

[quic_runs.zip](https://github.com/microsoft/msquic/files/7042396/quic_runs.zip)

**Comment by thhous-msft** [comment]
Just curious, how are you computing send time? The time from StreamSend to when you receive QUIC_STREAM_EVENT_SEND_COMPLETE?

With send buffering on, you will receive send complete almost instantly, whereas with send buffering off you won't receive the event until the data is actually acked.

**Comment by theandrewcross** [comment]
I should have probably explained that before, our goal is to have 8 frames of video "in flight" at any time and we use a semaphore to acheive this. So our pseudo-code would look something like :

`<---- Start timing here ---->
Wait for there to be <8 packets outstanding.
StreamSend(...)
[ in completion callback of StreamSend, signal one less packet outstanding]
<---- Finish timing here ---->`

In short, this is the time taken on average for there to be 8 packets kept in flight. While it is correct that with buffering that Quic responds immediately (as long as it's buffers are not full), we are sending to localhost and it is still taking 40ms for the sends to be completed on even very little data per send.

You can visually see a massive difference, one shows a huge number of dropped frames (because it is waiting 40ms for there to be space to send) and the other does not. 

When we revert to 1.4, this problem immediately goes away without any other code changes (I have unfortunately not tried the intermediate versions).

**Comment by nibanks** [comment]
So, you're comparing the above timing with send buffering enabled and with it disabled? By design, when send buffering is enabled, we copy the send internally and **immediately** complete the send to the app. When it's disabled, we don't copy and therefor don't complete the send until the peer has acknowledged receipt of the data. So it's expected (by design) that disabling send buffering would make the time between send and send complete take longer (1 round trip on average).

Is that's what's going on here? In the meantime, I'll look at the logs.

**Comment by nibanks** [comment]
There still aren't QUIC events in the ETL. Maybe instead of building the binary yourself, use the ones from the release zips?

**Comment by theandrewcross** [comment]
> By design, when send buffering is enabled, we copy the send internally and **immediately** complete the send to the app. 

I do understand this, however it only returns immediately if there is buffering within the quic libraries available to copy into. 

When not using buffering, we have 8 buffers in flight and it is taking 40ms for the one sent 8 buffers ago to be marked as having been sent ... and this is being sent to localhost (so the RTT should be essentially zero).

**Comment by nibanks** [comment]
> When not using buffering, we have 8 buffers in flight and it is taking 40ms for the one sent 8 buffers ago to be marked as having been sent ... and this is being sent to localhost (so the RTT should be essentially zero).

Interesting. I agree 40 ms seems like a long time over loopback. Logs would be really helpful here. If you can't get the logs to work locally, perhaps you can send me the stuff necessary to repro locally, over email?

**Comment by theandrewcross** [comment]
> There still aren't QUIC events in the ETL. Maybe instead of building the binary yourself, use the ones from the release zips?

![Events](https://user-images.githubusercontent.com/89476192/130700794-fcf12b63-9dff-49fc-9c69-67f5f4388f1a.png)

I see QUIC events in these ones.

**Comment by nibanks** [comment]
> I see QUIC events in these ones.

This is from those files? Let me check again....

**Comment by nibanks** [comment]
I think the largish delay is actually because of delayed ACKs. By default QUIC doesn't send an immediate acknowledgement in response to receiving a single packet. It sets a 25 ms timer, and either on the next packet or expiration of that timer does it send the ACK. I assume you don't have any traffic in the reverse direction?

**Comment by theandrewcross** [comment]
"I agree 40ms seems like a long time over loopback."

Unfortunately it is quite a bit worse than this because this is the 8th send waiting for the first send to complete. That means the "effective RTT" that would cause this is 8x40ms = 320ms

"I assume you don't have any traffic in the reverse direction?"

That is correct in this case. The interesting thing is that some of them complete very fast and others take about 40ms.

**Comment by thhous-msft** [comment]
Some being fast and some being slow actually brings more credibility to the delayed ack theory. With send buffering disabled, if the send side empties its buffer, its possible not enough is sent to cause an ack on the other end. If this happens, you'll see a delay waiting for the ack to get sent, none of the buffers on the send side will complete, even though their buffers have been sent. With send buffering disabled, you should be using QUIC_STREAM_EVENT_IDEAL_SEND_BUFFER_SIZE to figure out how much data to actually buffer, and buffer 2 times that send buffer size. That way data is always being sent, which keeps acks flowing back.

**Comment by theandrewcross** [comment]
Thank you so much for even considering this. I am going to look into this in much more depth and I am sure that I can find a fix. I truly appreciate your feedback and assistance and am just truly appreciative for the work you and your team are putting into this project.

**Comment by nibanks** [comment]
So, I suspect the confusion here is still coming from a misunderstanding of how things are working under the covers, and perhaps still a bit of confusion on my part on how your logic works.

Let's start with my understanding. You are trying to keep 8 sends pending at all times, right? Independent of buffering being enabled or not? And then you don't understand why you can sometimes have larger delays when buffering is disabled?

For your side of things, you've indicated you understand that send buffering in MsQuic just means that we will copy your send locally and immediately complete it, so long as we have space. Once we run out of space, we will pend the send; completing it only once we have space. The space is an estimation of what we believe should be _enough_ to saturate the network. We tweak that logic/calculation/heuristic over time so that might be one difference (when send buffering is enabled) you see between releases. We welcome feedback on this logic if you have any. Once we run out of space, it's only emptied once we get an acknowledgement for a previously copied send. Then we will copy in the pending send and complete it.

On the topic of acknowledgements, I've already indicated they are sent by the peer only after more than 1 packet is received OR the ACK delay (default of 25 ms) has elapsed. So if you only send 1 packet (< ~1450 bytes) less than every 25 ms, you essentially will always have a total ACK delay time of 25 ms + RTT. But you also have to account for possible packet loss. When that happens, things will be even longer. One (relatively) infrequent packet is kind of the worst-case scenario as far as latency around the ack.

So back to your scenario, I'm still a bit confused on your logic. Do you just pend 8 sends all at once or are you trying to space them out and have 8 per second or something like that?

Also, looking back at these logs, I am a bit confused. Why are there two connections? Is this over loopback? I don't think so because I see ~64K receives with no corresponding send, so I suspect the peer is not local.

![image](https://user-images.githubusercontent.com/20663557/130805515-c03b59b5-b8f5-4bcf-99ff-3fee50a17d9c.png)

BTW, from the logs, the average time between send (red spike) and ack (green spike) seems to be < 2 ms (quic_no_buffering.etl).

**Comment by theandrewcross** [comment]
I feel like I need to look into this much more at my level before I waste more of your time. I think that there is likely some interaction here between what we are doing and what the library is doing that is causing something to behave in a way that is not giving the results we expect. I think the onus is on us to look into this more and part of the benefit of msquic being open source is that we can do exactly that.
