### ISSUE TITLE
OpenSSL on Windows only supports loading RSA certificates from Windows Certificate Store

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#1942]
When loading a certificate from the Windows Certificate Store into OpenSSL on Windows, the code assumes the certificate has an RSA key.  This will fail to load non-RSA certificates.
Our OpenSSL-CAPI translation layer should at least support NIST curves for ECDH and ECDSA.

**Comment by bartonjs** [comment]
At around https://github.com/microsoft/msquic/blob/main/src/platform/cert_capi_openssl.c#L211 you'll want to do one of two things:

1) Change your export to be NCRYPT_PKCS8_PRIVATE_KEY_BLOB; read that in OpenSSL with something like

```C
PKCS8_PRIV_KEY_INFO* p8info =
    d2i_PKCS8_PRIV_KEY_INFO(NULL, &buf, len);

EVP_PKEY* key = EVP_PKCS82PKEY(p8info);
PKCS8_PRIV_KEY_INFO_free(p8info);

EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new(key, NULL);
Int check = EVP_PKEY_check(ctx);
EVP_PKEY_CTX_free(ctx);

if (check != 1 && check != -2) { error; }

return key;
```

or 2) ask the key what algorithm family it belongs to, and do the algorithm-appropriate export, instead of RSA.  Then you'll have to decode all of the MS blob formats and turn it into something OpenSSL can read... or, do (1).

**Comment by bartonjs** [comment]
Oh, I see, you chose (1) :smile:  Nevermind :smile:

**Comment by anrossi** [comment]
haha yeah, I looked into doing (2) first, and it looked daunting, so I decided to do (1) instead.
