### ISSUE TITLE
One-Way Delay Extensions

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [microsoft/msquic#2201]
### Describe the feature you'd like supported

Support for one-way delay timestamps, as described here: https://datatracker.ietf.org/doc/draft-huitema-quic-ts/

### Proposed solution

Unblocks the implementation of RMCAT algorithms (e.g., SCREAM)

**Comment by nibanks** [comment]
Items that need to be done for this extension:

1. New (preview) setting to enable one-way delay extension.
2. When setting is configured, we send the `enable_timestamp` transport parameter (`0x7158`) to value `3` to indicate we could like to send and receive `TIMESTAMP` frames (`757`).
3. When setting is configured, if we receive `enable_timestamp` TP, depending on the value, we cache whether we can send and recv `TIMESTAMP` frames.
4. Add support (and UT) for the `TIMESTAMP` frame, which just encoded number of microseconds since start of the `epoch` (i.e., connection).
5. If sending `TIMESTAMP` frames is negotiated, update ACK send logic to also write `TIMESTAMP` frame.
6. If recv `TIMESTAMP` frame: for first receive, calculate `phase_shift`, and for all, calculate `latest_1wd`.
7. Expose one-way delay to app (TODO: how?)
