### ISSUE TITLE
Make packages available for latest RHEL-based distributions

### ISSUE THREAD

**Issue by sbomer** [microsoft/msquic#3625]
### Describe the feature you'd like supported

I would like to install `libmsquic` on a RHEL-based (actually AlmaLinux 8) system. I found that it is available at `packages.microsoft.com` under `8.1` but not `8`, `9.0`, or `9`. It is also available under `centos/8`, but it would seem more appropriate to use the `rhel` sources on an AlmaLinux system.

I worked around this in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/e2ac99efb806885c8c253fa80aa65ca98e4ac3bb/src/almalinux/8/helix/amd64/Dockerfile#L3-L5 by using the `centos/8` feed. It would probably also work to use the `rhel/8.1` feed, but this doesn't seem ideal either because the `almalinux:8` image I'm using is already based on RHEL 8.7. I shouldn't have to add separate feeds for 8.x to get the latest packages for 8.

### Proposed solution

`libmsquic` should be added to the package feeds at https://packages.microsoft.com/rhel/8 and subsequent versions, or there should at least be simple documented instructions for installing the latest available `libmsquic` on each version of RHEL or RHEL-based distributions.

cc @richlander

**Comment by nibanks** [comment]
@wfurt I don't have a lot of understanding here. Would it be possible for you to help here?

**Comment by wfurt** [comment]
sure. cc few RedHat folks @tmds @omajid for guidance. 
From my prospective it would be preferable if the packages come from RH ecosystem.

**Comment by omajid** [comment]
For a package to be shipped by with RHEL, a number of people - including product management, engineering, support and - need to agree to ship and support it for a while. Without that buy-in, adding a new package to RHEL itself is a no-go. It is probably going to be more complicated by the fact that [OpenSSL 3 is planning to add QUIC support too](https://www.openssl.org/roadmap.html) and having two implementations of something in RHEL is generally not desired. If you folks really want to go down this route, you need to have some conversations with RHEL product management. Let me know if you want me to put you in touch with them. Or I suppose you can find the Microsoft-Red Hat partnership folks and go through them?

For community distributions (eg, Fedora, [EPEL - extra packages for RHEL](https://docs.fedoraproject.org/en-US/epel/)), it's generally a matter of someone stepping up to add the package and then maintain it in those environments. Guidance for Fedora: https://docs.fedoraproject.org/en-US/packaging-guidelines/. Guidance for EPEL: https://docs.fedoraproject.org/en-US/epel/epel-packaging/

I see that `libmsquic` is already a part of the Microsoft repository at https://packages.microsoft.com/rhel/8/prod/Packages/l/ so that's already done, right?

**Comment by csujedihy** [comment]
I think our goal is to just publish libmsquic for RHEL in our own package source (packages.microsoft.com), which is already done. We don't plan to get libmsquic shipped as part of RHEL.

We are publishing libmsquic to these repos since v2.2.2:
  - microsoft-rhel7.3-prod-yum
  - microsoft-rhel8.0-prod-yum
  - microsoft-rhel8.1-prod-yum
  - microsoft-rhel9.0-prod-yum

We can close this issue now. If .NET folks want us to publish libmsquic in more MSFT RHEL repos. Feel free to create an issue or send a PR to add the repo name to https://github.com/microsoft/msquic/blob/main/.azure/OneBranch.Publish.yml.
