### ISSUE TITLE
Support Reliable Stream Reset Extension

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#3775]
### Describe the feature you'd like supported

Let's add support for https://datatracker.ietf.org/doc/draft-ietf-quic-reliable-stream-reset/ to help the working group get interoperability coverage.

### Proposed solution

Implement the latest draft (not any non-error version though).

**Comment by ProjectsByJackHe** [comment]
Notes about the paper: 

o	Frame = digital data transmission unit, a container for a single network packet
o	There is already a RESET_STREAM frame used to reset a stream, can be sent by either client / server to abruptly terminate transmission on a stream. In that frame, there contains an error code. 
o	Reliable Stream Reset Extension 
	We want to implement a natural extension for RESET_STREAM: the CLOSE_STREAM frame. 
•	CLOSE_STREAM is nice because it guarantees reliable delivery of stream data up to a certain byte offset (what is the base of the offset?) 
o	I guess the base is implicit, because CLOSE_STREAM is RESET_STREAM with an added parameter; reliable size (RS). So it’s the portion of Final Size (FS) that is guaranteed to be delivered to the application. Like the first N bytes of final_size. 
	If a server receives CLOSE_STREAM, and (RS < FS), it’s normal, and will do what the server do to cleanup whatever and close connection (with no error?) once all reliable data has been ACKed. 
	If a server receives CLOSE_STREAM and (RS > FS), always close the connection with FRAME_ENCODING_ERROR. 
	I think the client does the same thing when receiving a CLOSE_STREAM frame? I am guessing MsQuic has API funcs that allow the client / server to send CLOSE_STREAM / RESET_STREAM at will whenever something goes wrong, all we need to do is implement the receiving behavior. 

•	Still does the same thing as RESET_STREAM, abruptly terminates transmission (can be sent by either client / server) with an error code if we send a CLOSE_STREAM of type 0x21.  
•	As a sender of CLOSE_STREAM frames, they MUST BE Acked before moving on (what does moving on mean in this context?), unless stream states changes to recvd.

	Sending a RESET_STREAM frame is equivalent to sending a CLOSE_STREAM frame with a reliable size of 0. 
	To support CLOSE_STREAM, I am guessing something has to remember reliable size, and normal STREAM frames with data up to the reliable size MUST be re-transmitted until we get an ACK?
	Sending multiple CLOSE_FRAMES in the same stream. 
In the draft RFC, [draft-ietf-quic-reliable-stream-reset-01 - Reliable QUIC Stream Resets](https://datatracker.ietf.org/doc/draft-ietf-quic-reliable-stream-reset/), in the section that talks about sending multiple CLOSE_STREAM frames in the same stream to reduce the reliable size, the sender shall not increase reliable size with each subsequent send. However, due to network delays causing reordering of packets, the receiver might get some packets with increasing reliable size. The paper says the receiver should just ignore them. Like once the receiver gets a CLOSE_STREAM frame, they will update some internal state (reliable size), close the stream. 
-	WHEN TO CLOSE A CONNECTION? 
o	There’s been many places in the paper that talks about closing the stream due to some error (Reliable size > final size), but I am having a hard time understanding the normal case. 
	Since we know CLOSE_FRAME (with reliable size = 0) == RESET FRAME, does this mean once all data has been received up to the reliable size byte offset, the client (or server?) can send a RESET_FRAME to close connection?
