### ISSUE TITLE
Add an option that allows for streams to getting auto-caneceled on packet loss.

### ISSUE THREAD

**Issue by sebastianpick** [microsoft/msquic#3984]
### Describe the feature you'd like supported

I'd like to request that a flag/option is added to streams that indicates to automatically close them if loss is detected. This is meant as an unreliable alternative to auto-resending lost segments/packets.

### Proposed solution

An alternative 'best effort'/unreliable option.

**Comment by nibanks** [comment]
API changes required (AFAICT):

- Add new `QUIC_SEND_FLAGS` to support automatic "abort on loss".
- Add a new event for streams to indicate an auto-abort has occurred and has an output parameter for the app to specify the error code (default to zero). The new event only happens if the app uses the new send flag.

Internal changes required:

- Streams save a new flag to indicate if the app has indicating it should be aborted if loss is encountered
- On loss, if the flag is set deliver the new event, and use the resulting error code to abort the stream (in both directions? silently?)

Then add tests for both no loss and loss scenarios.
