### ISSUE TITLE
Use platform independent enum for address family

### ISSUE THREAD

**Issue by rzikm** [microsoft/msquic#404]
Currently, the value of `AF_INET6` is system dependent. On Windows, it is 23 and on Linux, it is 10. When the library is used from a language like C#, which does not need separate compilation for different OSs, the caller needs to detect the running OS and select the correct value.

Since `AF_INET6` and related symbols are defined in OS headers, I suppose the solution would be defining a platform-independent enum for the address family.

**Comment by nibanks** [comment]
In order to not have to dynamically translate (at runtime) the address family values to the correct values, I want to continue having platform specific values for these. IMO, the real problem here is that the C# abstraction layer isn't properly providing per-platform values. @jkotalik do you agree? If so, it might be better to move this issue to dotnet.

**Comment by jkotalik** [comment]
What API is `AF_INET6` being passed in for? We could do the per-platform check in C# if necessary. However, from what it sounds like, maybe passing in an enum for IPV4, IPV6, etc may be better for this API?

**Comment by nibanks** [comment]
Generally, QUIC is going to be a pass through for this. Eventually it will be passed down directly to the UDP socket.

**Comment by rzikm** [comment]
>  IMO, the real problem here is that the C# abstraction layer isn't properly providing per-platform values. 

This is not about the current C# wrapper deep in .NET repo. I personally don't think it is ok for a cross-platform library to have different interface -- however slightly -- based on the platform, unless absolutely necessary.

This affects everyone writing code in a "portable" language like C#, Java, Python, and others capable of interop with C. It is likely that everyone will miss this difference and consider it a bug because such behavior is just unexpected, and use a platform check as a workaround for the issue.

I don't believe that avoiding runtime translation of this enum, in particular, justifies this. I would understand if it was some optional advanced feature available only on a particular system. However, address family is needed by every user.

If you still stand by your decision, could you please document any parts of the API that are platform-dependent in the way described in the original post? That way at least the unfortunate developers do not have to discover the discrepancies one by one.

**Comment by nibanks** [comment]
Let's standardize around the Windows format/values.

**Comment by ThadHouse** [comment]
So, I just spent a bit trying to do this, and its not as easy as it looks. Theres a lot of edge cases we'd have to handle here, and it gets especially hard both because of our helper functions, and because we don't actually ever manipulate the values in here internally. As an interop developer myself, I definitely agree with wanting this, but I think we need to discuss more if this is the right solution, or if theres another solution we should be taking that abstracts away even more.

**Comment by ThadHouse** [comment]
We needed to merge the API changes, which are #852 does. The linux side still needs to be updated to use the new values, but there were connection bugs.
