### ISSUE TITLE
Support Linux UDP Receive Segmentation

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#546]
### Describe the feature you'd like supported

Windows platform abstractions already support sending and receiving batches of UDP datagrams in a single call. Linux does not yet support this, and because of this, severely lacks in it's maximum throughput when compared to Windows.

### Proposed solution

There are existing UDP socket APIs [sendmmsg](https://linux.die.net/man/2/sendmmsg) and [recvmmsg](https://linux.die.net/man/2/recvmmsg) that should be wired up to the existing Linux platform data path abstraction.

**Comment by larseggert** [comment]
I think you want `sendmmsg` plus GSO, as @ghedo described [here](https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/).

**Comment by nibanks** [comment]
Thanks @larseggert. Specifically, something like this:
```C
setsockopt(fd, SOL_UDP, UDP_SEGMENT, &gso_size, sizeof(gso_size)))
```
and
```C
cm = CMSG_FIRSTHDR(&msg);
cm->cmsg_level = SOL_UDP;
cm->cmsg_type = UDP_SEGMENT;
cm->cmsg_len = CMSG_LEN(sizeof(uint16_t));
*((uint16_t *) CMSG_DATA(cm)) = gso_size;
```

**Comment by ThadHouse** [comment]
The batching part of this PR is now done. Renaming to segmentation.

**Comment by ThadHouse** [comment]
It turns out that URO doesn't work with recvmsg before linux 5.12, and even worse there is no way to detect this case. So if you try to detect URO, you might get only a half supported URO, which there is no way to detect, and might cause a massive perf regression. So until we can detect that case, or systems with that supported become more common, there isn't anything actionable on this issue.

However, because we have recv batching, and that works well, we likely wouldn't get a huge perf gain from this anyway. USO was the much more helpful item.
