### ISSUE TITLE
Copy symbols to shared folder on pipelines machine

### ISSUE THREAD

**Issue by anrossi** [microsoft/msquic#716]
When debugging kernel crashes in AZP runs, the single largest blocker is finding the right symbols for the specific msquic.sys that is running on that machine. 
If the symbols were copied to a folder with the same name as the AZP machine at the beginning of the test run, then it would be trivial to point the debugger at the right symbols. This would make it much faster to debug these issues.
The folder would have to be hosted on a device other than the machine running the kernel tests.

**Comment by ThadHouse** [comment]
Something I thing that might be worth trying is using `/Z7` instead of `/Zi` on the debug builds, at least for kernel mode. This embeds the debug symbols directly in the final object, rather then creating a PDB. Not sure if windbg would properly grab this however, or if that would still require grabbing the .sys file. If it still requires grabbing the .sys file, we have the same issue.

**Comment by nibanks** [comment]
We've had this open for ages and have lived without it. I'm just going to close this with no action.
