### ISSUE TITLE
Improve Interop Runner Logging

### ISSUE THREAD

**Issue by larseggert** [microsoft/msquic#863]
When running in the interop runner, the log has tons of messages like:
```
client          | [warning] Tracer discarded 58 events between [10:54:04.056212700] and [10:54:04.064362500] in trace UUID 9fab5ab4faa411c905b82a59bca6f25, within stream id 0. You should consider recording a new trace with larger buffers or with fewer events enabled.
```

**Comment by nibanks** [comment]
Currently blocked on interop runner support: https://github.com/marten-seemann/quic-interop-runner/issues/131. We need to replace streaming logs with explicit start/stop. I have this draft PR (https://github.com/microsoft/msquic/pull/856) but it doesn't work yet because of the dependency on the interop runner.

**Comment by nibanks** [comment]
We've been blocking on this for a long time with no change in sight. Just going to close this with no action.
