### ISSUE TITLE
Centos build instructions

### ISSUE THREAD

**Issue by DImuthuUpe** [microsoft/msquic#895]
### Describe the feature you'd like supported

Currently there are build instructions for ubuntu releases but some clusters are running on centos so it's better to have instructions for that platform as well

**Comment by ThadHouse** [comment]
Assuming you don't need logging, a standard cmake build on most linux distributions should work, with nothing special needed. Just make sure to clone all the submodules, and point to the root CMakeLists.txt. If you run into issues there, please create an issue for the specific issue you run into. 

If you want logging, as long as centos can install powershell and .NET Core, you should be able to pick apart the prepare-machine.ps1 script to see what is needed. Because of how different some linux distros are, providing detailed instructions for all distros is not very feasible.

**Comment by nibanks** [comment]
@DImuthuUpe if you have some specific error, please post it here. Otherwise let us know if things are working or not.

**Comment by nibanks** [comment]
Closing this for now. Please reactivate with your specific errors.
