### ISSUE TITLE
Support Android & iOS

### ISSUE THREAD

**Issue by lixt** [microsoft/msquic#952]
Along with Windows and Linux, is msquic be able to used on Android & iOS?

**Comment by nibanks** [comment]
@lixt currently MsQuic is only officially supported on Windows and Linux. We've done some prototyping with Android in the past, but don't have anything checked in. Eventually we'd like to support all platforms.

**Comment by lixt** [comment]
@nibanks Will Windows Phone be on the list?

**Comment by nibanks** [comment]
Not likely, unless someone else contributes a PR for it.

**Comment by DemiMarie** [comment]
@nibanks nit: Android technically runs on Linux :smile:.

**Comment by nibanks** [comment]
@DemiMarie yes, but there are enough differences that they have to be treated separately. For instance, from what I remember, certificate validation has to go through some Java API. Not sure.

**Comment by ThadHouse** [comment]
In theory, iOS is extremely close to working now. I was able to get a build with just slight build changes building for iOS, and got an app using it to link. Theres 1 small code change needed to be made. The issue I ran into is I couldn't actually get the library to own because of signing, and I don't know enough about macOS or iOS signing to bring this across the finish line. But its close enough someone with enough knowledge could easily make it work.

**Comment by ThadHouse** [comment]
Native binaries for Android are now being built with https://github.com/microsoft/msquic/pull/1835
Basic functionality has been tested as well. JNI and Java support is still necessary, but the binary does work with a Xamarin App.

**Comment by thhous-msft** [comment]
iOS support was added as of https://github.com/microsoft/msquic/pull/1904

**Comment by thhous-msft** [comment]
Since the native side of this is finished for both Android and iOS, I'm going to consider this complete. #1141 will track Java support, which will be the next part for Android.
